name: Workflow para CI

on:
  push:
    branches:
        - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: movistar-poc/org-core-workflows/.github/workflows/openshift-ci-onpremise.yml@main
